name: Procesado de la encuesta GeoChicas 8M

on:
  push:
    paths:
      - 'data/**'  # Cuando hay commit en la carpeta data
  workflow_dispatch:  # Ejecución manual

jobs:
  process-excel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: pip install pandas requests validators openpyxl

      - name: Run Excel Processing Script
        run: python procesar.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add data/
          git commit -m "Encuesta procesada"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
